version: '3'

services:
  api:
    build: .
    container_name: 'nest-api'
    environment:
      - DATABASE_URL=mysql://root:password@localhost:3306/mydb?schema=public
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

  db:
    image: 'mysql'
    container_name: 'database'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password