version: '3'

services:
  api:
    build: .
    container_name: 'nest-api'
    ports:
      - "3000:3000"

  db:
    image: 'mysql'
    container_name: 'database'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password