name: Build API

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the API Docker image
      run: docker build . --file Dockerfile --tag nest-api:$(date +%s)
